# Generated by Django 3.1.7 on 2022-09-23 19:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cntn',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cret_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='article',
            name='mdfy_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntn', models.CharField(max_length=10000)),
                ('cret_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('mdfy_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_board.article')),
            ],
        ),
    ]
